# **Table of contents**<a id='toc00_'></a> 
- [0. Imports](#toc0_)
    - [0.1. Packages and Libraries](#toc0_1_)
    - [0.2. Data](#toc0_2_)
- [1. Base Table Updates](#toc1_)
    - [1.1. Taxonomy](#toc1_1_)
    - [1.2. Realms](#toc1_2_)
    - [1.3. References](#toc1_3_)
- [2. Data Info](#toc2_)
    - [2.1. Observations](#toc2_1_)
    - [2.2. Native Data](#toc2_2_)
- [3. Tables Preparation](#toc3_)
    - [3.1. Native Data](#toc3_1_)
        - [3.1.1. Most Recent Equal Combinations](#toc3_1_1_)
        - [3.1.2. Update Table With Keys](#toc3_1_2_)
            - [3.1.2.1. Realm](#toc3_1_2_1_)
            - [3.1.2.2. Taxonomy](#toc3_1_2_2_)
            - [3.1.2.3. References](#toc3_1_2_3_)
    - [3.2. Observations Data](#toc3_2_)
        - [3.2.1. Update Table With Keys](#toc3_2_1_)
            - [3.2.1.1. Area - Geographical Region](#toc_3_2_1_1_)
            - [3.2.1.2. Realm](#toc_3_2_1_2_)
            - [3.2.1.3. Taxonomy](#toc_3_2_1_3_)
            - [3.2.1.4. References](#toc_3_2_1_4_)
- [4. Confirm Tables](#toc4_)
    - [4.1. Taxonomy](#toc4_1_)
    - [4.2. Area - Geographical Region](#toc4_2_)
    - [4.3. Realm](#toc4_3_)
    - [4.4. References](#toc4_4_)
    - [4.5. Natives](#toc4_5_)
    - [4.6. Observations](#toc4_6_)
- [5. Database Tables Export](#toc5_)
- [6. SQLite3 Database Creation](#toc6_)
    - [6.1. Create Connection](#toc6_1_)
    - [6.2. Taxonomy](#toc6_2_)
    - [6.3. Area - Geographical Region](#toc6_3_)
    - [6.4. Realm](#toc6_4_)
    - [6.5. References](#toc6_5_)
    - [6.6. Natives](#toc6_6_)
    - [6.7. Observations](#toc6_7_)
    - [6.8. Close Connector - Database Conclusion](#toc6_8_)

# <a id='toc0_'></a> [0. Imports](#toc00_)

## <a id='toc0_1_'></a> [0.1. Packages and Libraries](#toc0_)

In [1]:
import pandas as pd
import sqlite3
import os

/var/folders/tw/hvhv_1kn3hzdqm2b_3yzdh0r0000gn/T/ipykernel_68034/2375134969.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

## <a id='toc0_2_'></a> [0.2. Data](#toc0_)

All data manually retrieved, with the exception for TaxonomyData that was previously retrieved with TaxonomyExtract.ipynb

> *RawData* corresponds to the observations dataset

> *Regions* corresponds to the selected regions for the observations - roughly corresponding to the administrative areas by continent and insularity

> *Natives* corresponds to the native distribution of each species observed

In [2]:
RawData = pd.read_csv(r'../Data Raw/ObsList.csv', sep=';')
RawData.drop_duplicates(inplace=True)
RawData['Species'] = RawData['Species'].apply(lambda x: ' '.join(x.split()[:2]))
TaxonomyData = pd.read_csv(r'../Data Raw/TaxonomyRaw.csv')
TaxonomyData.drop_duplicates(inplace=True)
Regions = pd.read_csv(r'../Data Raw/RegionsTableData.csv', sep=';')
Regions.drop_duplicates(inplace=True)
Natives = pd.read_csv(r'../Data Raw/NativeRaw.csv', sep=';')
Natives.drop_duplicates(inplace=True)

In [3]:
RawData.head(5)

,Species,Area,Realm,Cryptogenic,Introduced,Dispersal,Established,Eradicated,Intentional_Release,Year,Reference Year,Reference
0,Spodoptera eridania,Brazil,Neotropical,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
1,Phyllocnistis citrella,Brazil,Neotropical,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
2,Hypsipyla grandella,Brazil,Neotropical,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
3,Spodoptera eridania,United States,Nearctic,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
4,Hyphantria cunea,United States,Nearctic,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...

In [4]:
TaxonomyData.head(5)

,Species,AcceptedSpecies,Family,Genus
0,Spodoptera eridania,Spodoptera eridania,Noctuidae,Spodoptera
1,Phyllocnistis citrella,Phyllocnistis citrella,Gracillariidae,Phyllocnistis
2,Hypsipyla grandella,Hypsipyla grandella,Pyralidae,Hypsipyla
3,Hyphantria cunea,Hyphantria cunea,Erebidae,Hyphantria
4,Phthorimaea operculella,Phthorimaea operculella,Gelechiidae,Phthorimaea

In [5]:
Regions.head(5)

    AreaID              AreaName               Country Continent SubContinent
0  AFG.1_1           Afghanistan           Afghanistan      Asia          NaN
1  AGO.1_1                Angola                Angola    Africa          NaN
2  ALB.1_1               Albania               Albania    Europe          NaN
3  AND.1_1               Andorra               Andorra    Europe          NaN
4  ARE.1_1  United Arab Emirates  United Arab Emirates      Asia          NaN

In [6]:
Natives.head(5)

,Unnamed: 0,Species,Continent,Realm,Cosmopolitan,Reference Year,Reference,AcceptedSpecies
0,0,Bleszynskia malacelloides,Australia,Australian,0,2001,"Hoare, R. (2001). Adventive species of Lepidop...",Bleszynskia malacelloides
1,1,Artigisa melanephele,Australia,Australian,0,2001,"Hoare, R. (2001). Adventive species of Lepidop...",Artigisa melanephele
2,2,Acrocercops laciniella,Australia,Australian,0,2001,"Hoare, R. (2001). Adventive species of Lepidop...",Acrocercops laciniella
3,3,Zomariana doxasticana,Australia,Australian,0,2001,"Hoare, R. (2001). Adventive species of Lepidop...",Zomariana doxasticana
4,4,Coleophora striatipennella,Europe,Palearctic,0,2001,"Hoare, R. (2001). Adventive species of Lepidop...",Coleophora striatipennella

# <a id='toc1_'></a> [1. Base Tables Updates](#toc00_)

Besides the Regions (Geographical Regions) base table there were no tables fully prepared for the construction of the database.

We started by separating the data that was fully merged on the observation table onto separate parts. Composing: Taxonomy, Realms and References.

## <a id='toc1_1_'></a> [1.1. Taxonomy](#toc1_)

In [7]:
TaxonomyData['SpeciesID'] = 'SP' + (TaxonomyData.index +1).astype(str)

In [8]:
species_to_id = dict(zip(TaxonomyData['Species'], TaxonomyData['SpeciesID']))
TaxonomyData['AcceptedSpeciesID'] = TaxonomyData['AcceptedSpecies'].map(species_to_id)

In [9]:
missing_mask = TaxonomyData['AcceptedSpeciesID'].isnull()
missing_species = TaxonomyData[missing_mask]['AcceptedSpecies'].unique()

new_rows = []
for species in missing_species:
    ref_row = TaxonomyData[TaxonomyData['AcceptedSpecies'] == species].iloc[0]
    new_rows.append({
        'Species': species,
        'AcceptedSpecies': species,
        'Genus': ref_row['Genus'],
        'Family': ref_row['Family']})

if new_rows:
    new_df = pd.DataFrame(new_rows)
    TaxonomyData = pd.concat([TaxonomyData, new_df], ignore_index=True)

TaxonomyData['SpeciesID'] = 'SP' + (TaxonomyData.index + 1).astype(str)

species_to_id = dict(zip(TaxonomyData['Species'], TaxonomyData['SpeciesID']))
TaxonomyData['AcceptedSpeciesID'] = TaxonomyData['AcceptedSpecies'].map(species_to_id)

In [10]:
TaxonomyData.head(5)

,Species,AcceptedSpecies,Family,Genus,SpeciesID,AcceptedSpeciesID
0,Spodoptera eridania,Spodoptera eridania,Noctuidae,Spodoptera,SP1,SP1
1,Phyllocnistis citrella,Phyllocnistis citrella,Gracillariidae,Phyllocnistis,SP2,SP2
2,Hypsipyla grandella,Hypsipyla grandella,Pyralidae,Hypsipyla,SP3,SP3
3,Hyphantria cunea,Hyphantria cunea,Erebidae,Hyphantria,SP4,SP4
4,Phthorimaea operculella,Phthorimaea operculella,Gelechiidae,Phthorimaea,SP5,SP5

In [11]:
valid_species_ids = set(TaxonomyData[TaxonomyData['SpeciesID'] == TaxonomyData['AcceptedSpeciesID']]['SpeciesID'])
invalid_IDs = TaxonomyData[TaxonomyData['SpeciesID'] != TaxonomyData['AcceptedSpeciesID']][~TaxonomyData[TaxonomyData['SpeciesID'] != TaxonomyData['AcceptedSpeciesID']]['AcceptedSpeciesID'].isin(valid_species_ids)]

print("Invalid synonyms with missing AcceptedSpeciesID:")
print(invalid_IDs)

Invalid synonyms with missing AcceptedSpeciesID:
Empty DataFrame
Columns: [Species, AcceptedSpecies, Family, Genus, SpeciesID, AcceptedSpeciesID]
Index: []

## <a id='toc1_2_'></a> [1.2. Realms](#toc1_)

In [12]:
RealmObs = RawData[['Realm']].copy()
RealmNat = Natives[['Realm']].copy()

Realms = pd.concat([RealmObs, RealmNat]).drop_duplicates().reset_index(drop=True)
Realms['RealmID'] = 'RLM' + (Realms.index +1).astype(str)

In [13]:
Realms

             Realm RealmID
0      Neotropical    RLM1
1         Nearctic    RLM2
2         Oceanina    RLM3
3         Oriental    RLM4
4    Sino-Japanese    RLM5
5     Afrotropical    RLM6
6       Palearctic    RLM7
7       Australian    RLM8
8       Panamanian    RLM9
9   Saharo-Arabian   RLM10
10      Madagascan   RLM11

## <a id='toc1_3_'></a> [1.3. References](#toc1_)

In [14]:
ReferencesObs = RawData[['Reference Year', 'Reference']].copy()
ReferencesObs.drop_duplicates(inplace=True)
ReferencesObs.reset_index(drop=True, inplace=True)

In [15]:
ReferencesObs.head(5)

   Reference Year                                          Reference
0            2024  CAB International (CABI) (2024). CABI Invasive...
1            2020  Gilligan, T., Brown, J. and Baixeras, J. (2020...
2            2024  European and Mediterranean Plant Protection Or...
3            2009  Fodor, E. and Haruta, O. (2009). Niche partiti...
4            2010  Heard, T., Elliott, L., Anderson, B., White, L...

In [16]:
ReferencesNat = Natives[['Reference Year', 'Reference']].copy()
ReferencesNat.drop_duplicates(inplace=True)
ReferencesNat.reset_index(drop=True, inplace=True)

In [17]:
ReferencesNat

     Reference Year                                          Reference
0              2001  Hoare, R. (2001). Adventive species of Lepidop...
1              1992  Frank, J. and McCoy, E. (1992). Introduction t...
2              2010  Lopez-Vaamonde, C., Agassiz, D., Augustin, S.,...
3              2020  Gilligan, T., Brown, J. and Baixeras, J. (2020...
4              2022  Calhoun, J. and Smith, R. (2022). Brephidium e...
..              ...                                                ...
720            1960  Gozmany L. (1960). The results of the zoologic...
721            2017  Cock, M. (2017) A preliminary catalogue of the...
722            1987  Diakonoff, A. and van Nieukerken, E. (1987). E...
723            2003  Baran, T. (2003). Scythris buszkoi sp. n., a n...
724            2017  Dawidowicz, L. and Rozwalka, R. (2017). Anatra...

[725 rows x 2 columns]

In [18]:
References = pd.concat([ReferencesObs, ReferencesNat]).drop_duplicates().reset_index(drop=True)

In [19]:
References['ReferenceID'] = 'REF' + (References.index +1).astype(str)

In [20]:
References

,Reference Year,Reference,ReferenceID
0,2024,CAB International (CABI) (2024). CABI Invasive...,REF1
1,2020,"Gilligan, T., Brown, J. and Baixeras, J. (2020...",REF2
2,2024,European and Mediterranean Plant Protection Or...,REF3
3,2009,"Fodor, E. and Haruta, O. (2009). Niche partiti...",REF4
4,2010,"Heard, T., Elliott, L., Anderson, B., White, L...",REF5
...,...,...,...
1099,2023,"Assaad, M. (2023). Ecology and impacts of inse...",REF1100
1100,1960,Gozmany L. (1960). The results of the zoologic...,REF1101
1101,2017,"Cock, M. (2017) A preliminary catalogue of the...",REF1102
1102,1987,"Diakonoff, A. and van Nieukerken, E. (1987). E...",REF1103
1103,2003,"Baran, T. (2003). Scythris buszkoi sp. n., a n...",REF1104

# <a id='toc2_'></a> [2. Data Info](#toc00_)

## <a id='toc2_1_'></a> [2.1. Observations](#toc2_)

In [21]:
RawData.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16491 entries, 0 to 21189
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Species              16491 non-null  object
 1   Area                 16491 non-null  object
 2   Realm                16491 non-null  object
 3   Cryptogenic          4428 non-null   float64
 4   Introduced           7168 non-null   float64
 5   Dispersal            646 non-null    float64
 6   Established          16291 non-null  float64
 7   Eradicated           16447 non-null  float64
 8   Intentional_Release  4590 non-null   float64
 9   Year                 3055 non-null   float64
 10  Reference Year       16491 non-null  int64
 11  Reference            16491 non-null  object
dtypes: float64(7), int64(1), object(4)
memory usage: 1.6+ MB

In [22]:
RawData.describe().T

,count,mean,std,min,25%,50%,75%,max
Cryptogenic,4428.0,0.144083,0.351214,0.0,0.0,0.0,0.0,1.0
Introduced,7168.0,0.970145,0.170199,0.0,1.0,1.0,1.0,1.0
Dispersal,646.0,0.701238,0.458070,0.0,0.0,1.0,1.0,1.0
Established,16291.0,0.968326,0.175136,0.0,1.0,1.0,1.0,1.0
Eradicated,16447.0,0.003891,0.062261,0.0,0.0,0.0,0.0,1.0
Intentional_Release,4590.0,0.054466,0.226960,0.0,0.0,0.0,0.0,1.0
Year,3055.0,1974.600982,51.212779,1565.0,1958.0,1991.0,2008.0,2024.0
Reference Year,16491.0,2020.439694,6.374995,1926.0,2020.0,2024.0,2024.0,2025.0

In [23]:
RawData.describe(include = 'O').T

,count,unique,top,freq
Species,16491,1552,Spodoptera frugiperda,378
Area,16491,233,United States,1011
Realm,16491,11,Palearctic,7264
Reference,16491,503,European and Mediterranean Plant Protection Or...,4657

In [24]:
RawData.columns

Index(['Species', 'Area', 'Realm', 'Cryptogenic', 'Introduced', 'Dispersal',
       'Established', 'Eradicated', 'Intentional_Release', 'Year',
       'Reference Year', 'Reference'],
      dtype='object')

## <a id='toc2_2_'></a> [2.2. Native Data](#toc2_)

In [25]:
Natives.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7759 entries, 0 to 7758
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       7759 non-null   int64
 1   Species          7759 non-null   object
 2   Continent        7757 non-null   object
 3   Realm            7759 non-null   object
 4   Cosmopolitan     7759 non-null   int64
 5   Reference Year   7759 non-null   int64
 6   Reference        7759 non-null   object
 7   AcceptedSpecies  7759 non-null   object
dtypes: int64(3), object(5)
memory usage: 485.1+ KB

In [26]:
Natives.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,7759.0,3879.000000,2239.974702,0.0,1939.5,3879.0,5818.5,7758.0
Cosmopolitan,7759.0,0.000516,0.022701,0.0,0.0,0.0,0.0,1.0
Reference Year,7759.0,2008.989947,16.444980,1775.0,2007.0,2008.0,2020.0,2025.0

In [27]:
Natives.describe(include = 'O').T

,count,unique,top,freq
Species,7759,917,Lampides boeticus,133
Continent,7757,7,Europe,3422
Realm,7759,11,Palearctic,4079
Reference,7759,725,"Khramov, P. (Ed.) (2007). Insecta.pro: interna...",2205
AcceptedSpecies,7759,907,Lampides boeticus,133

In [28]:
Natives.columns

Index(['Unnamed: 0', 'Species', 'Continent', 'Realm', 'Cosmopolitan',
       'Reference Year', 'Reference', 'AcceptedSpecies'],
      dtype='object')

# <a id='toc3_'></a> [3. Tables Preparation](#toc00_)

Before we start inputing data onto the database we need to prepare the tables for all of them to have the predefined structure. We needed to update the fields for it to have the connections with the ID's.

## <a id='toc3_1_'></a> [3.1. Native Data](#toc3_)

In [29]:
Natives_DB = Natives[['Species', 'AcceptedSpecies', 'Continent', 'Realm', 'Cosmopolitan', 'Reference Year', 'Reference']].copy()

### <a id='toc3_1_1_'></a> [3.1.1. Most Recent Equal Combinations](#toc3_1_)

In [30]:
idx = Natives_DB.groupby(['AcceptedSpecies', 'Continent', 'Realm', 'Cosmopolitan'])['Reference Year'].idxmax()

Natives_DB = Natives_DB.loc[idx].reset_index(drop=True)

### <a id='toc3_1_2_'></a> [3.1.2. Update Table with Keys](#toc3_1_)

#### <a id='toc3_1_2_1_'></a> [3.1.2.1. Realm](#toc3_1_2_)

In [31]:
Natives_DB = Natives_DB.merge(Realms, on='Realm', how='left')
Natives_DB.drop(columns='Realm', inplace=True)

#### <a id='toc3_1_2_2_'></a> [3.1.2.2. Taxonomy](#toc3_1_2_)

In [32]:
Natives_DB.drop(columns='AcceptedSpecies', inplace=True)
Natives_DB = Natives_DB.merge(TaxonomyData, on='Species', how='left')

In [33]:
Natives_DB.drop(columns=['Species', 'AcceptedSpecies', 'Genus', 'Family', 'AcceptedSpeciesID'], inplace=True)

#### <a id='toc3_1_2_3_'></a> [3.1.2.3. References](#toc3_1_2_)

In [34]:
Natives_DB.drop(columns='Reference Year', inplace=True)
Natives_DB = Natives_DB.merge(References, on='Reference', how='left')
Natives_DB.drop(columns=['Reference', 'Reference Year'], inplace=True)

## <a id='toc3_2_'></a> [3.2. Observations Data](#toc3_)

In [35]:
Observations_DB = RawData[['Species', 'Area', 'Realm', 'Cryptogenic', 'Introduced', 'Dispersal',
       'Established', 'Eradicated', 'Intentional_Release', 'Year',
       'Reference Year', 'Reference']].copy()

### <a id='toc3_2_1_'></a> [3.2.1. Update Table With Keys](#toc3_2_)

#### <a id='toc3_2_1_1_'></a> [3.2.1.1. Area - Geographical Regions](#toc3_2_1_)

In [36]:
RegionsData = Regions[['AreaID', 'AreaName', 'Country', 'Continent', 'SubContinent']].copy()

In [37]:
Observations_DB = Observations_DB.merge(RegionsData, left_on='Area', right_on='AreaName', how='left')
Observations_DB.drop(columns=['AreaName', 'Area', 'Country', 'Continent', 'SubContinent'], inplace=True)

#### <a id='toc3_2_1_2_'></a> [3.2.1.2. Realm](#toc3_2_1_)

In [38]:
Observations_DB = Observations_DB.merge(Realms, on='Realm', how='left')
Observations_DB.drop(columns='Realm', inplace=True)

#### <a id='toc3_2_1_3_'></a> [3.2.1.3. Taxonomy](#toc3_2_1_)

In [39]:
Observations_DB = Observations_DB.merge(TaxonomyData, on='Species', how='left')
Observations_DB.drop(columns=['Species', 'AcceptedSpecies', 'Genus', 'Family', 'AcceptedSpeciesID'], inplace=True)

#### <a id='toc3_2_1_4_'></a> [3.2.1.4. References](#toc3_2_1_)

In [40]:
Observations_DB.drop(columns='Reference Year', inplace=True)
Observations_DB = Observations_DB.merge(References, on='Reference', how='left')
Observations_DB.drop(columns=['Reference', 'Reference Year'], inplace=True)

# <a id='toc4_'></a> [4. Confirm Tables](#toc00_)

## <a id='toc4_1_'></a> [4.1. Taxonomy](#toc00_)

In [41]:
TaxonomyData.head(5)

,Species,AcceptedSpecies,Family,Genus,SpeciesID,AcceptedSpeciesID
0,Spodoptera eridania,Spodoptera eridania,Noctuidae,Spodoptera,SP1,SP1
1,Phyllocnistis citrella,Phyllocnistis citrella,Gracillariidae,Phyllocnistis,SP2,SP2
2,Hypsipyla grandella,Hypsipyla grandella,Pyralidae,Hypsipyla,SP3,SP3
3,Hyphantria cunea,Hyphantria cunea,Erebidae,Hyphantria,SP4,SP4
4,Phthorimaea operculella,Phthorimaea operculella,Gelechiidae,Phthorimaea,SP5,SP5

In [42]:
TaxonomyData.columns

Index(['Species', 'AcceptedSpecies', 'Family', 'Genus', 'SpeciesID',
       'AcceptedSpeciesID'],
      dtype='object')

In [43]:
TaxonomyData.describe().T

                  count unique                  top freq
Species            1635   1635  Spodoptera eridania    1
AcceptedSpecies    1635   1394   Etainia sericopeza    3
Family             1631     74          Tortricidae  199
Genus              1632    806           Coleophora   28
SpeciesID          1635   1635                  SP1    1
AcceptedSpeciesID  1635   1394               SP1308    3

In [44]:
TaxonomyData.describe(include = 'O').T

                  count unique                  top freq
Species            1635   1635  Spodoptera eridania    1
AcceptedSpecies    1635   1394   Etainia sericopeza    3
Family             1631     74          Tortricidae  199
Genus              1632    806           Coleophora   28
SpeciesID          1635   1635                  SP1    1
AcceptedSpeciesID  1635   1394               SP1308    3

## <a id='toc4_2_'></a> [4.2. Area - Geographical Region](#toc00_)

In [45]:
RegionsData.head(5)

    AreaID              AreaName               Country Continent SubContinent
0  AFG.1_1           Afghanistan           Afghanistan      Asia          NaN
1  AGO.1_1                Angola                Angola    Africa          NaN
2  ALB.1_1               Albania               Albania    Europe          NaN
3  AND.1_1               Andorra               Andorra    Europe          NaN
4  ARE.1_1  United Arab Emirates  United Arab Emirates      Asia          NaN

In [46]:
RegionsData.columns

Index(['AreaID', 'AreaName', 'Country', 'Continent', 'SubContinent'], dtype='object')

In [47]:
RegionsData.describe().T

             count unique        top freq
AreaID         258    258    AFG.1_1    1
AreaName       258    241      Spain    4
Country        258    205     France    8
Continent      258      8     Africa   64
SubContinent    22      3  Polynesia    9

In [48]:
RegionsData.describe(include = 'O').T

             count unique        top freq
AreaID         258    258    AFG.1_1    1
AreaName       258    241      Spain    4
Country        258    205     France    8
Continent      258      8     Africa   64
SubContinent    22      3  Polynesia    9

## <a id='toc4_3_'></a> [4.3. Realms](#toc00_)

In [49]:
Realms.head(5)

           Realm RealmID
0    Neotropical    RLM1
1       Nearctic    RLM2
2       Oceanina    RLM3
3       Oriental    RLM4
4  Sino-Japanese    RLM5

In [50]:
Realms.columns

Index(['Realm', 'RealmID'], dtype='object')

In [51]:
Realms.describe().T

        count unique          top freq
Realm      11     11  Neotropical    1
RealmID    11     11         RLM1    1

In [52]:
Realms.describe(include = 'O').T

        count unique          top freq
Realm      11     11  Neotropical    1
RealmID    11     11         RLM1    1

## <a id='toc4_4_'></a> [4.4. References](#toc00_)

In [53]:
References.head(5)

,Reference Year,Reference,ReferenceID
0,2024,CAB International (CABI) (2024). CABI Invasive...,REF1
1,2020,"Gilligan, T., Brown, J. and Baixeras, J. (2020...",REF2
2,2024,European and Mediterranean Plant Protection Or...,REF3
3,2009,"Fodor, E. and Haruta, O. (2009). Niche partiti...",REF4
4,2010,"Heard, T., Elliott, L., Anderson, B., White, L...",REF5

In [54]:
References.columns

Index(['Reference Year', 'Reference', 'ReferenceID'], dtype='object')

In [55]:
References.describe().T

,count,mean,std,min,25%,50%,75%,max
Reference Year,1104.0,2005.134964,21.603173,1775.0,2000.0,2012.0,2019.0,2025.0

In [56]:
References.describe(include = 'O').T

,count,unique,top,freq
Reference,1104,1104,CAB International (CABI) (2024). CABI Invasive...,1
ReferenceID,1104,1104,REF1,1

## <a id='toc4_5_'></a> [4.5. Natives](#toc00_)

In [57]:
Natives_DB.head(5)

       Continent  Cosmopolitan RealmID SpeciesID ReferenceID
0  North America             0    RLM2     SP398      REF505
1  North America             0    RLM9     SP398      REF505
2         Africa             0   RLM10     SP982      REF148
3           Asia             0    RLM7     SP982      REF506
4           Asia             0   RLM10     SP982      REF506

In [58]:
Natives_DB.columns

Index(['Continent', 'Cosmopolitan', 'RealmID', 'SpeciesID', 'ReferenceID'], dtype='object')

In [59]:
Natives_DB.describe().T

               count      mean       std  min  25%  50%  75%  max
Cosmopolitan  2195.0  0.001822  0.042659  0.0  0.0  0.0  0.0  1.0

In [60]:
Natives_DB.describe(include = 'O').T

            count unique    top freq
Continent    2195      7   Asia  765
RealmID      2195     11   RLM7  633
SpeciesID    2182    904  SP143   14
ReferenceID  2195    644   REF1  106

## <a id='toc4_6_'></a> [4.6. Observations](#toc00_)

In [61]:
Observations_DB.head(5)

,Cryptogenic,Introduced,Dispersal,Established,Eradicated,Intentional_Release,Year,AreaID,RealmID,SpeciesID,ReferenceID
0,NaN,NaN,NaN,1.0,0.0,NaN,NaN,BRA.1_1,RLM1,SP1,REF1
1,NaN,NaN,NaN,1.0,0.0,NaN,NaN,BRA.1_1,RLM1,SP2,REF1
2,NaN,NaN,NaN,1.0,0.0,NaN,NaN,BRA.1_1,RLM1,SP3,REF1
3,NaN,NaN,NaN,1.0,0.0,NaN,NaN,USA.1_1,RLM2,SP1,REF1
4,NaN,NaN,NaN,1.0,0.0,NaN,NaN,USA.1_2,RLM2,SP1,REF1

In [62]:
Observations_DB.columns

Index(['Cryptogenic', 'Introduced', 'Dispersal', 'Established', 'Eradicated',
       'Intentional_Release', 'Year', 'AreaID', 'RealmID', 'SpeciesID',
       'ReferenceID'],
      dtype='object')

In [63]:
Observations_DB.describe().T

,count,mean,std,min,25%,50%,75%,max
Cryptogenic,6407.0,0.138286,0.345227,0.0,0.0,0.0,0.0,1.0
Introduced,9053.0,0.972274,0.164195,0.0,1.0,1.0,1.0,1.0
Dispersal,926.0,0.718143,0.450147,0.0,0.0,1.0,1.0,1.0
Established,20396.0,0.968915,0.173550,0.0,1.0,1.0,1.0,1.0
Eradicated,20693.0,0.003866,0.062059,0.0,0.0,0.0,0.0,1.0
Intentional_Release,6849.0,0.047014,0.211685,0.0,0.0,0.0,0.0,1.0
Year,4356.0,1970.691690,58.239446,1565.0,1953.0,1989.0,2007.0,2024.0

In [64]:
Observations_DB.describe(include = 'O').T

             count unique      top  freq
AreaID       18706    232  USA.1_2  1011
RealmID      20752     11     RLM7  8977
SpeciesID    20752   1552      SP8   437
ReferenceID  20752    503     REF3  5506

# <a id='toc5_'></a> [5. Database Tables Exportation](#toc00_)

In [65]:
TaxonomyData.to_csv(r'../Database Tables/Base_Taxonomy.csv', index=False)
RegionsData.to_csv(r'../Database Tables/Geography_Regions.csv', index=False)
Realms.to_csv(r'../Database Tables/Geography_Realms.csv', index=False)
References.to_csv(r'../Database Tables/Base_References.csv', index=False)
Natives_DB.to_csv(r'../Database Tables/Obs_NativesDB.csv', index=False)
Observations_DB.to_csv(r'../Database Tables/Obs_ObservationsDB.csv', index=False)

# <a id='toc6_'></a> [6. SQLite3 Database Creation](#toc00_)

## <a id='toc6_1_'></a> [6.1. Create Connection](#toc00_)

In [66]:
con = sqlite3.connect("../Database/ENNLWD.db")
con.execute("PRAGMA foreign_keys = ON")

In [67]:
cur = con.cursor()

In [68]:
tables_check = cur.execute("SELECT name FROM sqlite_master")
tables_check.fetchall()

[]

## <a id='toc6_2_'></a> [6.2. Taxonomy](#toc00_)

In [69]:
TaxonomyData = TaxonomyData[['SpeciesID', 'AcceptedSpeciesID', 'Species', 'AcceptedSpecies', 'Genus', 'Family']]
TaxonomyData = TaxonomyData.reset_index(drop=True)

In [70]:
cur.execute("""CREATE TABLE IF NOT EXISTS Taxonomy (
    SpeciesID VARCHAR(7) PRIMARY KEY, 
    AcceptedSpeciesID VARCHAR(7),
    Species TEXT, 
    AcceptedSpecies TEXT, 
    Genus TEXT, 
    Family TEXT,
    FOREIGN KEY (AcceptedSpeciesID) REFERENCES Taxonomy(SpeciesID) ON DELETE SET NULL)
    """)

In [71]:
cols = ['SpeciesID', 'AcceptedSpeciesID', 'Species', 'AcceptedSpecies', 'Genus', 'Family']

In [72]:
BaseTaxonomy = TaxonomyData[TaxonomyData['SpeciesID'] == TaxonomyData['AcceptedSpeciesID']]
BaseTaxonomy = BaseTaxonomy[cols]
BaseTaxonomy.to_sql('Taxonomy', con, if_exists='append', index=False)
con.commit()

In [73]:
ComposedTaxonomy = TaxonomyData[TaxonomyData['SpeciesID'] != TaxonomyData['AcceptedSpeciesID']]
ComposedTaxonomy = ComposedTaxonomy[cols]
ComposedTaxonomy.to_sql('Taxonomy', con, if_exists='append', index=False)
con.commit

In [74]:
Taxonomy_check = cur.execute("SELECT * FROM Taxonomy")
Taxonomy_check.fetchone()

('SP1',
 'SP1',
 'Spodoptera eridania',
 'Spodoptera eridania',
 'Spodoptera',
 'Noctuidae')

In [75]:
#cur.execute("""DROP TABLE Taxonomy""")

## <a id='toc6_3_'></a> [6.3. Area - Geographical Region](#toc00_)

In [76]:
RegionsData = RegionsData[['AreaID', 'AreaName', 'Country', 'Continent', 'SubContinent']]
RegionsData = RegionsData.reset_index(drop=True)

In [77]:
cur.execute("""CREATE TABLE IF NOT EXISTS Regions (
    AreaID VARCHAR(8) PRIMARY KEY, 
    AreaName TEXT, 
    Country TEXT, 
    Continent TEXT, 
    SubContinent TEXT)
    """)

In [78]:
RegionsData.to_sql('Regions', con, if_exists='append', index=False)
con.commit()

In [79]:
Regions_check = cur.execute('SELECT * FROM "Regions"')
Regions_check.fetchone()

('AFG.1_1', 'Afghanistan', 'Afghanistan', 'Asia', None)

In [80]:
#cur.execute("""DROP TABLE Regions""")

## <a id='toc6_4_'></a> [6.4. Realms](#toc00_)

In [81]:
Realms = Realms[['RealmID', 'Realm']]
Realms = Realms.reset_index(drop=True)

In [82]:
cur.execute("""CREATE TABLE IF NOT EXISTS Realms (
    RealmID VARCHAR(5) PRIMARY KEY, 
    Realm TEXT)
    """)

In [83]:
Realms.to_sql('Realms', con, if_exists='append', index=False)
con.commit()

In [84]:
Realms_check = cur.execute('SELECT * FROM "Realms"')
Realms_check.fetchone()

('RLM1', 'Neotropical')

In [85]:
#cur.execute("""DROP TABLE Realms""")

## <a id='toc6_5_'></a> [6.5. References](#toc00_)

In [86]:
References = References[['ReferenceID', 'Reference', 'Reference Year']]
References = References.reset_index(drop=True)

In [87]:
cur.execute("""CREATE TABLE IF NOT EXISTS "References" (
    ReferenceID VARCHAR(7) PRIMARY KEY, 
    Reference TEXT, 
    "Reference Year" INTEGER
)""")

In [88]:
References.to_sql('References', con, if_exists='append', index=False)
con.commit()

In [89]:
References_check = cur.execute('SELECT * FROM "References"')
References_check.fetchone()

('REF1',
 'CAB International (CABI) (2024). CABI Invasive Species Compendium. Available at: https://www.cabidigitallibrary.org/product/QI',
 2024)

In [90]:
#cur.execute('DROP TABLE "References"')

## <a id='toc6_6_'></a> [6.6. Natives](#toc00_)

In [91]:
Natives_DB = Natives_DB[['SpeciesID', 'RealmID', 'Continent', 'Cosmopolitan', 'ReferenceID']]
Natives_DB = Natives_DB.reset_index(drop=True)

In [92]:
cur.execute("""
CREATE TABLE IF NOT EXISTS NativeDistribution (
    SpeciesID VARCHAR(7), 
    RealmID VARCHAR(5), 
    Continent TEXT,
    Cosmopolitan INTEGER CHECK (Cosmopolitan IN (0, 1) OR Cosmopolitan IS NULL),
    ReferenceID VARCHAR(7), 
    FOREIGN KEY (SpeciesID) REFERENCES Taxonomy(SpeciesID) ON DELETE SET NULL,
    FOREIGN KEY (RealmID) REFERENCES Realms(RealmID) ON DELETE SET NULL,
    FOREIGN KEY (ReferenceID) REFERENCES "References"(ReferenceID) ON DELETE SET NULL
)""")

In [93]:
Natives_DB.to_sql('NativeDistribution', con, if_exists='append', index=False)
con.commit()

In [94]:
NativeDist_check = cur.execute('SELECT * FROM NativeDistribution')
NativeDist_check.fetchone()

('SP398', 'RLM2', 'North America', 0, 'REF505')

In [95]:
#cur.execute('DROP TABLE NativeDistribution')

## <a id='toc6_7_'></a> [6.7. Observations](#toc00_)

In [96]:
Observations_DB = Observations_DB[['SpeciesID', 'AreaID', 'RealmID', 
                                   'Cryptogenic', 'Introduced', 'Dispersal', 'Established', 'Eradicated', 
                                   'ReferenceID']]
Observations_DB = Observations_DB.reset_index(drop=True)

In [97]:
cur.execute("""
CREATE TABLE IF NOT EXISTS Observations (
    SpeciesID VARCHAR(7),
    AreaID VARCHAR(8), 
    RealmID VARCHAR(5), 
    Cryptogenic INTEGER CHECK (Cryptogenic IN (0, 1) OR Cryptogenic IS NULL),
    Introduced INTEGER CHECK (Introduced IN (0, 1) OR Introduced IS NULL),
    Dispersal INTEGER CHECK (Dispersal IN (0, 1) OR Dispersal IS NULL),
    Established INTEGER CHECK (Established IN (0, 1) OR Established IS NULL),
    Eradicated INTEGER CHECK (Eradicated IN (0, 1) OR Eradicated IS NULL),
    ReferenceID VARCHAR(7),
    FOREIGN KEY (SpeciesID) REFERENCES Taxonomy(SpeciesID) ON DELETE SET NULL,
    FOREIGN KEY (AreaID) REFERENCES Regions(AreaID) ON DELETE SET NULL,
    FOREIGN KEY (RealmID) REFERENCES Realms(RealmID) ON DELETE SET NULL,
    FOREIGN KEY (ReferenceID) REFERENCES "References"(ReferenceID) ON DELETE SET NULL
)""")

In [98]:
Observations_DB.to_sql('Observations', con, if_exists='append', index=False)
con.commit()

In [99]:
Observations_check = cur.execute('SELECT * FROM Observations')
Observations_check.fetchone()

('SP1', 'BRA.1_1', 'RLM1', None, None, None, 1, 0, 'REF1')

In [100]:
#cur.execute('DROP TABLE Observations')

## <a id='toc6_8_'></a> [6.8. Close Connector - Database Conclusion](#toc00_)

In [101]:
con.close()

In [102]:
os.rename(r'../Database/ENNLWD.db', r'../Database/ENNLWD.sqlite')

In [103]:
con = sqlite3.connect("../Database/ENNLWD.sqlite")
cur = con.cursor()

In [104]:
tables_check = cur.execute("SELECT name FROM sqlite_master")
tables_check.fetchall()

[('Taxonomy',),
 ('sqlite_autoindex_Taxonomy_1',),
 ('Regions',),
 ('sqlite_autoindex_Regions_1',),
 ('Realms',),
 ('sqlite_autoindex_Realms_1',),
 ('References',),
 ('sqlite_autoindex_References_1',),
 ('NativeDistribution',),
 ('Observations',)]

In [105]:
con.close()