# Table of Contents

- [0. Imports](#0-imports)
    - [0.1. Package and Libraries](#01-packages-and-libraries)
    - [0.2. Data](#02-data)
- [1. Base Tables Updates](#1-base-table-updates)
    - [1.1. Taxonomy](#11-taxonomy)
    - [1.2. Realms](#12-realms)
    - [1.3. References](#13-references)
- [2. Data Info](#2-data-info)
    - [2.1. Observations](#21-observations)
    - [2.2. Native Data](#22-native-data)
- [3. Tables Preparation](#3-tables-preparation)
    - [3.1. Native Data](#31-native-data)
        - [3.1.1. Update Table with Keys](#311-update-table-with-keys)
            - [3.1.1.1. Realm](#3111-realm)
            - [3.1.1.2. Taxonomy](#3112-taxonomy)
            - [3.1.1.3. References](#3113-references)
        - [3.1.2. Reorder Columns](#312-reorder-columns)
    - [3.2. Observations Data](#32-observations-data)
        - [3.2.1. Update Table with Keys](#321-update-table-with-keys)
            - [3.2.1.1. Area - Geographical Regions](#3211-area---geographical-regions)
            - [3.2.1.2. Realm](#3212-realm)
            - [3.2.1.3. Taxonomy](#3213-taxonomy)
            - [3.2.1.4. References](#3214-references)
        - [3.2.2. Reorder Columns](#322-reorder-columns)
- [4. Confirm Tables](#4-confirm-tables)
    - [4.1. Taxonomy](#41-taxonomy)
    - [4.2. Area - Geographical Region](#42-area---geographical-region)
    - [4.3. Realms](#43-realms)
    - [4.4. References](#44-references)
    - [4.5. Natives](#45-natives)
    - [4.6. Observations](#46-observations)
- [5. Database Tables Exportation](#5-database-tables-exportation)
- [6. SQLite3 Database Creation](#6-sqlite3-database-creation)
    - [6.1. Create Connection](#61-create-connection)
    - [6.2. Taxonomy](#62-taxonomy)
    - [6.3. Area - Geographical Region](#63-area---geographical-region)
    - [6.4. Realms](#64-realms)
    - [6.5. References](#65-references)
    - [6.6. Natives](#66-natives)
    - [6.7. Observations](#67-observations)
    - [6.8. Close Connector - Database Conclusion](#68-close-connector---database-conclusion)

# [0. Imports](#table-of-contents)

## [0.1. Packages and Libraries](#table-of-contents)

In [1]:
import pandas as pd
import sqlite3
import os

## [0.2. Data](#table-of-contents)

All data manually retrieved, with the exception for TaxonomyData that was previously retrieved with TaxonomyExtract.ipynb

> *RawData* corresponds to the observations dataset after cleaning

> *Regions* corresponds to the selected regions for the observations - roughly corresponding to the administrative areas by continent and insularity

> *Natives* corresponds to the native distribution of each species observed

In [2]:
RawData = pd.read_csv(r'../Transformed Data/ObservationsClean.csv', sep=';', encoding='utf-8')
RawData['Species'] = RawData['Species'].apply(lambda x: ' '.join(x.split()[:2]))

TaxonomyData = pd.read_csv(r'../Transformed Data/TaxonomyClean.csv', sep=';', encoding='utf-8')

Regions = pd.read_csv(r'../Data Raw/RegionsTableData.csv', sep=';', encoding='utf-8')
Regions.drop_duplicates(inplace=True)

Natives = pd.read_csv(r'../Transformed Data/NativeDataClean.csv', sep=';', encoding='utf-8')

References = pd.read_csv(r'../Transformed Data/ReferencesClean.csv', sep=';', encoding='utf-8')

In [3]:
RawData.head(5)

,Species,NAME_0,Realm,Cryptogenic,Dispersal,Eradicated,IntentionalRelease,Introduced,Established,ReportedFirstYear,Reference,ReferenceYear,AcceptedSpecies
0,Ostrinia nubilalis,Canada,Nearctic,NaN,NaN,0.0,NaN,NaN,1.0,NaN,CAB International (CABI) (2024). CABI Invasive...,2024,Ostrinia nubilalis
1,Zeiraphera diniana,Canada,Nearctic,NaN,NaN,0.0,NaN,NaN,1.0,NaN,CAB International (CABI) (2024). CABI Invasive...,2024,Zeiraphera griseana
2,Plutella xylostella,Canada,Nearctic,NaN,NaN,0.0,NaN,NaN,1.0,NaN,CAB International (CABI) (2024). CABI Invasive...,2024,Plutella xylostella
3,Helicoverpa armigera,Brazil,Neotropical,NaN,NaN,0.0,NaN,NaN,1.0,NaN,CAB International (CABI) (2024). CABI Invasive...,2024,Helicoverpa armigera
4,Spodoptera exempta,Seychelles,Oceanina,NaN,NaN,0.0,NaN,NaN,1.0,NaN,CAB International (CABI) (2024). CABI Invasive...,2024,Spodoptera exempta

In [4]:
TaxonomyData.head(5)

                Species       AcceptedSpecies        Genus       Family
0    Ostrinia nubilalis    Ostrinia nubilalis     Ostrinia    Crambidae
1    Zeiraphera diniana   Zeiraphera griseana   Zeiraphera  Tortricidae
2   Plutella xylostella   Plutella xylostella     Plutella  Plutellidae
3  Helicoverpa armigera  Helicoverpa armigera  Helicoverpa    Noctuidae
4    Spodoptera exempta    Spodoptera exempta   Spodoptera    Noctuidae

In [5]:
Regions.head(5)

,AreaID,AreaName,Country,Continent,SubContinent
0,ATA.1_1,Antarctica,Antarctica,Antarctica,NaN
1,NOR.2_1,Norway Antactic Islands,Norway,Antarctica,NaN
2,FRA.4_1,French Antarctic Islands,France,Antarctica,NaN
3,AUS.4_1,Australian Antarctic Territories,Australia,Antarctica,NaN
4,GBR.2_1,British Antarctic Islands,United Kingdom,Antarctica,NaN

In [6]:
Natives.head(5)

,Cosmopolitan,Continent,Species,Realm,ReferenceYear,Reference,AcceptedSpecies
0,0,Asia,Chilo infuscatellus,Saharo-Arabian,2024,"Li, A., et al. (2024). Sugarcane borers: speci...",Chilo infuscatellus
1,0,Asia,Actias selene,Saharo-Arabian,2007,"Choldumrongkul, S., et al. (2007). Geographica...",Actias selene
2,0,Asia,Caloptilia roscipennella,Saharo-Arabian,2024,"de Prins, J., de Prins, W. (2024). Global Taxo...",Caloptilia roscipennella
3,0,Asia,Elophila nymphaeata,Saharo-Arabian,1984,"Speidel, W. (1984). Revision der Acentropinae ...",Elophila nymphaeata
4,0,Asia,Papilio demoleus,Saharo-Arabian,2020,"Riaz, S., et al. (2020). Morphology, life cycl...",Papilio demoleus

# [1. Base Table Updates](#table-of-contents)

## [1.1. Taxonomy](#table-of-contents)

In [7]:
TaxonomyData['SpeciesID'] = 'SP' + (TaxonomyData.index +1).astype(str)

In [8]:
species_to_id = dict(zip(TaxonomyData['Species'], TaxonomyData['SpeciesID']))
TaxonomyData['AcceptedSpeciesID'] = TaxonomyData['AcceptedSpecies'].map(species_to_id)

In [9]:
TaxonomyData.head(5)

,Species,AcceptedSpecies,Genus,Family,SpeciesID,AcceptedSpeciesID
0,Ostrinia nubilalis,Ostrinia nubilalis,Ostrinia,Crambidae,SP1,SP1
1,Zeiraphera diniana,Zeiraphera griseana,Zeiraphera,Tortricidae,SP2,SP1003
2,Plutella xylostella,Plutella xylostella,Plutella,Plutellidae,SP3,SP3
3,Helicoverpa armigera,Helicoverpa armigera,Helicoverpa,Noctuidae,SP4,SP4
4,Spodoptera exempta,Spodoptera exempta,Spodoptera,Noctuidae,SP5,SP5

In [10]:
TaxonomyData = TaxonomyData[['SpeciesID', 'AcceptedSpeciesID', 'Species', 'AcceptedSpecies', 'Genus', 'Family']]

## [1.2. Realms](#table-of-contents)

In [11]:
RealmObs = RawData[['Realm']].copy()
RealmNat = Natives[['Realm']].copy()

Realms = pd.concat([RealmObs, RealmNat]).drop_duplicates().reset_index(drop=True).dropna()
Realms['RealmID'] = 'RLM' + (Realms.index +1).astype(str)

In [12]:
Realms = Realms[['RealmID', 'Realm']]

## [1.3. References](#table-of-contents)

In [13]:
References.head(5)

                                           Reference  Reference Year
0  Li, A., et al. (2024). Sugarcane borers: speci...            2024
1  Choldumrongkul, S., et al. (2007). Geographica...            2007
2  de Prins, J., de Prins, W. (2024). Global Taxo...            2024
3  Speidel, W. (1984). Revision der Acentropinae ...            1984
4  Riaz, S., et al. (2020). Morphology, life cycl...            2020

In [14]:
References['ReferenceID'] = 'REF' + (References.index +1).astype(str)

In [15]:
References.rename(columns={'Reference Year': 'ReferenceYear', 'Reference': 'BibliographicReference'}, inplace=True)

In [16]:
References = References[['ReferenceID', 'BibliographicReference', 'ReferenceYear']]

# [2. Data Info](#table-of-contents)

## [2.1. Observations](#table-of-contents)

In [17]:
RawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17445 entries, 0 to 17444
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Species             17445 non-null  object
 1   NAME_0              17445 non-null  object
 2   Realm               17445 non-null  object
 3   Cryptogenic         4587 non-null   float64
 4   Dispersal           653 non-null    float64
 5   Eradicated          17401 non-null  float64
 6   IntentionalRelease  4653 non-null   float64
 7   Introduced          7136 non-null   float64
 8   Established         17255 non-null  float64
 9   ReportedFirstYear   2994 non-null   float64
 10  Reference           17445 non-null  object
 11  ReferenceYear       17445 non-null  int64
 12  AcceptedSpecies     17445 non-null  object
dtypes: float64(7), int64(1), object(5)
memory usage: 1.7+ MB

In [18]:
RawData.describe().T

,count,mean,std,min,25%,50%,75%,max
Cryptogenic,4587.0,0.146283,0.353428,0.0,0.0,0.0,0.0,1.0
Dispersal,653.0,0.698315,0.459341,0.0,0.0,1.0,1.0,1.0
Eradicated,17401.0,0.004540,0.067228,0.0,0.0,0.0,0.0,1.0
IntentionalRelease,4653.0,0.054374,0.226778,0.0,0.0,0.0,0.0,1.0
Introduced,7136.0,0.970291,0.169794,0.0,1.0,1.0,1.0,1.0
Established,17255.0,0.968473,0.174742,0.0,1.0,1.0,1.0,1.0
ReportedFirstYear,2994.0,1976.954910,50.431234,1565.0,1962.0,1994.0,2009.0,2024.0
ReferenceYear,17445.0,2020.821496,6.215518,1926.0,2020.0,2024.0,2024.0,2025.0

In [19]:
RawData.describe(include = 'O').T

,count,unique,top,freq
Species,17445,1400,Spodoptera frugiperda,525
NAME_0,17445,232,United States,1804
Realm,17445,11,Palearctic,6902
Reference,17445,492,European and Mediterranean Plant Protection Or...,5104
AcceptedSpecies,17445,1257,Spodoptera frugiperda,525

In [20]:
RawData.columns

Index(['Species', 'NAME_0', 'Realm', 'Cryptogenic', 'Dispersal', 'Eradicated',
       'IntentionalRelease', 'Introduced', 'Established', 'ReportedFirstYear',
       'Reference', 'ReferenceYear', 'AcceptedSpecies'],
      dtype='object')

## [2.2. Native Data](#table-of-contents)

In [21]:
Natives.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2769 entries, 0 to 2768
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Cosmopolitan     2769 non-null   int64
 1   Continent        2758 non-null   object
 2   Species          2769 non-null   object
 3   Realm            2762 non-null   object
 4   ReferenceYear    2769 non-null   int64
 5   Reference        2769 non-null   object
 6   AcceptedSpecies  2769 non-null   object
dtypes: int64(2), object(5)
memory usage: 151.6+ KB

In [22]:
Natives.describe().T

,count,mean,std,min,25%,50%,75%,max
Cosmopolitan,2769.0,0.005417,0.073415,0.0,0.0,0.0,0.0,1.0
ReferenceYear,2769.0,2006.507403,21.352364,1775.0,2003.0,2012.0,2020.0,2025.0

In [23]:
Natives.describe(include = 'O').T

,count,unique,top,freq
Continent,2758,7,Asia,974
Species,2769,1034,Lampides boeticus,15
Realm,2762,11,Palearctic,812
Reference,2769,780,"Khramov, P. (Ed.) (2007). Insecta.pro: interna...",156
AcceptedSpecies,2769,1034,Lampides boeticus,15

In [24]:
Natives.columns

Index(['Cosmopolitan', 'Continent', 'Species', 'Realm', 'ReferenceYear',
       'Reference', 'AcceptedSpecies'],
      dtype='object')

# [3. Tables Preparation](#table-of-contents)

## [3.1. Native Data](#table-of-contents)

In [25]:
Natives

,Cosmopolitan,Continent,Species,Realm,ReferenceYear,Reference,AcceptedSpecies
0,0,Asia,Chilo infuscatellus,Saharo-Arabian,2024,"Li, A., et al. (2024). Sugarcane borers: speci...",Chilo infuscatellus
1,0,Asia,Actias selene,Saharo-Arabian,2007,"Choldumrongkul, S., et al. (2007). Geographica...",Actias selene
2,0,Asia,Caloptilia roscipennella,Saharo-Arabian,2024,"de Prins, J., de Prins, W. (2024). Global Taxo...",Caloptilia roscipennella
3,0,Asia,Elophila nymphaeata,Saharo-Arabian,1984,"Speidel, W. (1984). Revision der Acentropinae ...",Elophila nymphaeata
4,0,Asia,Papilio demoleus,Saharo-Arabian,2020,"Riaz, S., et al. (2020). Morphology, life cycl...",Papilio demoleus
...,...,...,...,...,...,...,...
2764,0,Asia,Parapoynx diminutalis,Saharo-Arabian,1996,"Buckingham, G., Bennett, C. (1996). Laboratory...",Parapoynx diminutalis
2765,0,Asia,Parapoynx diminutalis,Palearctic,1996,"Buckingham, G., Bennett, C. (1996). Laboratory...",Parapoynx diminutalis
2766,0,Africa,Sphenarches caffer,Madagascan,1910,"Fletcher, T. (1910). Lepidoptera exclusive of ...",Sphenarches caffer
2767,0,Asia,Sphenarches caffer,Oriental,1910,"Fletcher, T. (1910). Lepidoptera exclusive of ...",Sphenarches caffer
2768,0,Australia,Sphenarches caffer,Australian,1910,"Fletcher, T. (1910). Lepidoptera exclusive of ...",Sphenarches caffer

In [26]:
Natives_DB = Natives[['Species', 'Continent', 'Realm', 'Cosmopolitan', 'Reference']].copy()
Natives_DB.rename(columns={'Reference': 'BibliographicReference'}, inplace=True)

### [3.1.1. Update Table with Keys](#table-of-contents)

#### [3.1.1.1. Realm](#table-of-contents)

In [27]:
Natives_DB = Natives_DB.merge(Realms, on='Realm', how='left')
Natives_DB.drop(columns='Realm', inplace=True)

#### [3.1.1.2. Taxonomy](#table-of-contents)

In [28]:
Natives_DB = Natives_DB.merge(TaxonomyData, on='Species', how='left')

In [29]:
Natives_DB.drop(columns=['Species', 'AcceptedSpecies', 'Genus', 'Family', 'AcceptedSpeciesID'], inplace=True)

#### [3.1.1.3. References](#table-of-contents)

In [30]:
Natives_DB = Natives_DB.merge(References, on='BibliographicReference', how='left')
Natives_DB.drop(columns=['BibliographicReference', 'ReferenceYear'], inplace=True)

### [3.1.2. Reorder Columns](#table-of-contents)

In [31]:
Natives_DB = Natives_DB[['SpeciesID', 'RealmID', 'Continent', 'Cosmopolitan', 'ReferenceID']]

## [3.2. Observations Data](#table-of-contents)

In [32]:
RawData.rename(columns={'ReportedFirstYear': 'Year', 
                        'NAME_0': 'Area', 
                        'Reference': 'BibliographicReference'}, inplace=True)

In [33]:
Observations_DB = RawData[['Species', 
                           'Area', 'Realm',
                           'Cryptogenic', 'Introduced', 'Dispersal',
                           'Established', 'Eradicated', 'IntentionalRelease', 'Year',
                           'BibliographicReference']].copy()

### [3.2.1. Update Table With Keys](#table-of-contents)

#### [3.2.1.1. Area - Geographical Regions](#table-of-contents)

In [34]:
RegionsData = Regions[['AreaID', 'AreaName', 'Country', 'Continent', 'SubContinent']].copy()

In [35]:
Observations_DB = Observations_DB.merge(RegionsData, left_on='Area', right_on='AreaName', how='left')
Observations_DB.drop(columns=['AreaName', 'Area', 'Country', 'Continent', 'SubContinent'], inplace=True)

#### [3.2.1.2. Realm](#table-of-contents)

In [36]:
Observations_DB = Observations_DB.merge(Realms, on='Realm', how='left')
Observations_DB.drop(columns='Realm', inplace=True)

#### [3.2.1.3. Taxonomy](#table-of-contents)

In [37]:
Observations_DB = Observations_DB.merge(TaxonomyData, on='Species', how='left')
Observations_DB.drop(columns=['Species', 'AcceptedSpecies', 'Genus', 'Family', 'AcceptedSpeciesID'], inplace=True)

#### [3.2.1.4. References](#table-of-contents)

In [38]:
Observations_DB = Observations_DB.merge(References, on='BibliographicReference', how='left')
Observations_DB.drop(columns=['BibliographicReference', 'ReferenceYear'], inplace=True)

### [3.2.2. Reorder Columns](#table-of-contents)

In [39]:
Observations_DB = Observations_DB[['SpeciesID', 'AreaID', 'RealmID',
                                  'Cryptogenic', 'IntentionalRelease', 'Introduced', 'Dispersal', 'Established', 'Eradicated', 
                                  'Year', 'ReferenceID']]

In [40]:
Observations_DB

,SpeciesID,AreaID,RealmID,Cryptogenic,IntentionalRelease,Introduced,Dispersal,Established,Eradicated,Year,ReferenceID
0,SP1,CAN.1_1,RLM1,NaN,NaN,NaN,NaN,1.0,0.0,NaN,REF23
1,SP2,CAN.1_1,RLM1,NaN,NaN,NaN,NaN,1.0,0.0,NaN,REF23
2,SP3,CAN.1_1,RLM1,NaN,NaN,NaN,NaN,1.0,0.0,NaN,REF23
3,SP4,BRA.1_1,RLM2,NaN,NaN,NaN,NaN,1.0,0.0,NaN,REF23
4,SP5,SYC.1_1,RLM3,NaN,NaN,NaN,NaN,1.0,0.0,NaN,REF23
...,...,...,...,...,...,...,...,...,...,...,...
17461,SP576,JPN.1_1,RLM5,0.0,0.0,1.0,0.0,1.0,0.0,NaN,REF780
17462,SP576,MDG.1_1,RLM11,0.0,0.0,1.0,0.0,1.0,0.0,NaN,REF780
17463,SP576,KOR.1_1,RLM7,0.0,0.0,1.0,0.0,1.0,0.0,NaN,REF780
17464,SP238,USA.1_1,RLM1,0.0,0.0,1.0,NaN,1.0,NaN,1976.0,REF15
17465,SP238,PAN.1_1,RLM9,0.0,0.0,1.0,NaN,1.0,NaN,NaN,REF15

In [41]:
Observations_DB['Cryptogenic'] = Observations_DB['Cryptogenic'].astype('Int64')
Observations_DB['IntentionalRelease'] = Observations_DB['IntentionalRelease'].astype('Int64')
Observations_DB['Introduced'] = Observations_DB['Introduced'].astype('Int64')
Observations_DB['Dispersal'] = Observations_DB['Dispersal'].astype('Int64')
Observations_DB['Established'] = Observations_DB['Established'].astype('Int64')
Observations_DB['Eradicated'] = Observations_DB['Eradicated'].astype('Int64')
Observations_DB['Year'] = Observations_DB['Year'].astype('Int64')

# [4. Confirm Tables](#table-of-contents)

## [4.1. Taxonomy](#table-of-contents)

In [42]:
TaxonomyData.head(5)

,SpeciesID,AcceptedSpeciesID,Species,AcceptedSpecies,Genus,Family
0,SP1,SP1,Ostrinia nubilalis,Ostrinia nubilalis,Ostrinia,Crambidae
1,SP2,SP1003,Zeiraphera diniana,Zeiraphera griseana,Zeiraphera,Tortricidae
2,SP3,SP3,Plutella xylostella,Plutella xylostella,Plutella,Plutellidae
3,SP4,SP4,Helicoverpa armigera,Helicoverpa armigera,Helicoverpa,Noctuidae
4,SP5,SP5,Spodoptera exempta,Spodoptera exempta,Spodoptera,Noctuidae

In [43]:
TaxonomyData.columns

Index(['SpeciesID', 'AcceptedSpeciesID', 'Species', 'AcceptedSpecies', 'Genus',
       'Family'],
      dtype='object')

In [44]:
TaxonomyData.describe().T

                  count unique                       top freq
SpeciesID          1470   1470                       SP1    1
AcceptedSpeciesID  1470   1257                    SP1277    4
Species            1470   1470        Ostrinia nubilalis    1
AcceptedSpecies    1470   1257  Paraswammerdamia lutarea    4
Genus              1470    758                Coleophora   22
Family             1470     71               Tortricidae  186

In [45]:
TaxonomyData.describe(include = 'O').T

                  count unique                       top freq
SpeciesID          1470   1470                       SP1    1
AcceptedSpeciesID  1470   1257                    SP1277    4
Species            1470   1470        Ostrinia nubilalis    1
AcceptedSpecies    1470   1257  Paraswammerdamia lutarea    4
Genus              1470    758                Coleophora   22
Family             1470     71               Tortricidae  186

## [4.2. Area - Geographical Region](#table-of-contents)

In [46]:
RegionsData.head(5)

,AreaID,AreaName,Country,Continent,SubContinent
0,ATA.1_1,Antarctica,Antarctica,Antarctica,NaN
1,NOR.2_1,Norway Antactic Islands,Norway,Antarctica,NaN
2,FRA.4_1,French Antarctic Islands,France,Antarctica,NaN
3,AUS.4_1,Australian Antarctic Territories,Australia,Antarctica,NaN
4,GBR.2_1,British Antarctic Islands,United Kingdom,Antarctica,NaN

In [47]:
RegionsData.columns

Index(['AreaID', 'AreaName', 'Country', 'Continent', 'SubContinent'], dtype='object')

In [48]:
RegionsData.describe().T

             count unique                            top freq
AreaID         258    258                        ATA.1_1    1
AreaName       258    257  US Oceania Micronesia Islands    2
Country        258    205                         France    8
Continent      258      8                         Africa   64
SubContinent    22      3                      Polynesia    9

In [49]:
RegionsData.describe(include = 'O').T

             count unique                            top freq
AreaID         258    258                        ATA.1_1    1
AreaName       258    257  US Oceania Micronesia Islands    2
Country        258    205                         France    8
Continent      258      8                         Africa   64
SubContinent    22      3                      Polynesia    9

## [4.3. Realms](#table-of-contents)

In [50]:
Realms.head(5)

  RealmID          Realm
0    RLM1       Nearctic
1    RLM2    Neotropical
2    RLM3       Oceanina
3    RLM4       Oriental
4    RLM5  Sino-Japanese

In [51]:
Realms.columns

Index(['RealmID', 'Realm'], dtype='object')

In [52]:
Realms.describe().T

        count unique       top freq
RealmID    11     11      RLM1    1
Realm      11     11  Nearctic    1

In [53]:
Realms.describe(include = 'O').T

        count unique       top freq
RealmID    11     11      RLM1    1
Realm      11     11  Nearctic    1

## [4.4. References](#table-of-contents)

In [54]:
References.head(5)

,ReferenceID,BibliographicReference,ReferenceYear
0,REF1,"Li, A., et al. (2024). Sugarcane borers: speci...",2024
1,REF2,"Choldumrongkul, S., et al. (2007). Geographica...",2007
2,REF3,"de Prins, J., de Prins, W. (2024). Global Taxo...",2024
3,REF4,"Speidel, W. (1984). Revision der Acentropinae ...",1984
4,REF5,"Riaz, S., et al. (2020). Morphology, life cycl...",2020

In [55]:
References.columns

Index(['ReferenceID', 'BibliographicReference', 'ReferenceYear'], dtype='object')

In [56]:
References.describe().T

,count,mean,std,min,25%,50%,75%,max
ReferenceYear,1139.0,2004.532924,23.158989,1775.0,1999.0,2012.0,2019.0,2025.0

In [57]:
References.describe(include = 'O').T

,count,unique,top,freq
ReferenceID,1139,1139,REF1,1
BibliographicReference,1139,1138,"Zalucki, M., et al. (2007). Will biological co...",2

## [4.5. Natives](#table-of-contents)

In [58]:
Natives_DB.head(5)

  SpeciesID RealmID Continent  Cosmopolitan ReferenceID
0    SP1028   RLM10      Asia             0        REF1
1     SP848   RLM10      Asia             0        REF2
2     SP181   RLM10      Asia             0        REF3
3    SP1093   RLM10      Asia             0        REF4
4      SP72   RLM10      Asia             0        REF5

In [59]:
Natives_DB.columns

Index(['SpeciesID', 'RealmID', 'Continent', 'Cosmopolitan', 'ReferenceID'], dtype='object')

In [60]:
Natives_DB.describe().T

               count      mean       std  min  25%  50%  75%  max
Cosmopolitan  2770.0  0.005415  0.073402  0.0  0.0  0.0  0.0  1.0

In [61]:
Natives_DB.describe(include = 'O').T

            count unique    top freq
SpeciesID    2770   1034  SP105   15
RealmID      2763     11   RLM7  812
Continent    2759      7   Asia  974
ReferenceID  2770    781  REF27  156

## [4.6. Observations](#table-of-contents)

In [62]:
Observations_DB.head(5)

,SpeciesID,AreaID,RealmID,Cryptogenic,IntentionalRelease,Introduced,Dispersal,Established,Eradicated,Year,ReferenceID
0,SP1,CAN.1_1,RLM1,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23
1,SP2,CAN.1_1,RLM1,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23
2,SP3,CAN.1_1,RLM1,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23
3,SP4,BRA.1_1,RLM2,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23
4,SP5,SYC.1_1,RLM3,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23

In [63]:
Observations_DB.columns

Index(['SpeciesID', 'AreaID', 'RealmID', 'Cryptogenic', 'IntentionalRelease',
       'Introduced', 'Dispersal', 'Established', 'Eradicated', 'Year',
       'ReferenceID'],
      dtype='object')

In [64]:
Observations_DB.describe().T

,count,mean,std,min,25%,50%,75%,max
Cryptogenic,4589.0,0.146219,0.353364,0.0,0.0,0.0,0.0,1.0
IntentionalRelease,4655.0,0.054565,0.227154,0.0,0.0,0.0,0.0,1.0
Introduced,7140.0,0.970308,0.169748,0.0,1.0,1.0,1.0,1.0
Dispersal,654.0,0.697248,0.459801,0.0,0.0,1.0,1.0,1.0
Established,17276.0,0.968453,0.174795,0.0,1.0,1.0,1.0,1.0
Eradicated,17422.0,0.004534,0.067188,0.0,0.0,0.0,0.0,1.0
Year,2994.0,1976.95491,50.431234,1565.0,1962.0,1994.0,2009.0,2024.0

In [65]:
Observations_DB.describe(include = 'O').T

             count unique      top  freq
SpeciesID    17466   1400     SP14   525
AreaID       17460    232  USA.1_1  1804
RealmID      17466     11     RLM7  6902
ReferenceID  17466    493   REF781  5116

# [5. Database Tables Exportation](#table-of-contents)

In [66]:
TaxonomyData.to_csv(r'../Database Tables/Base_Taxonomy.csv', index=False, sep=";", encoding='utf-8', lineterminator='\n')
RegionsData.to_csv(r'../Database Tables/Geography_Regions.csv', index=False, sep=";", encoding='utf-8', lineterminator='\n')
Realms.to_csv(r'../Database Tables/Geography_Realms.csv', index=False, sep=";", encoding='utf-8', lineterminator='\n')
References.to_csv(r'../Database Tables/Base_References.csv', index=False, sep=";", encoding='utf-8', lineterminator='\n')
Natives_DB.to_csv(r'../Database Tables/Obs_NativesDB.csv', index=False, sep=";", encoding='utf-8', lineterminator='\n')
Observations_DB.to_csv(r'../Database Tables/Obs_ObservationsDB.csv', index=False, sep=";", encoding='utf-8', lineterminator='\n')

# [6. SQLite3 Database Creation](#table-of-contents)

## [6.1. Create Connection](#table-of-contents)

In [67]:
con = sqlite3.connect("../Database/ENNLWD.db")
con.execute("PRAGMA foreign_keys = ON")

In [68]:
cur = con.cursor()

In [69]:
tables_check = cur.execute("SELECT name FROM sqlite_master")
tables_check.fetchall()

[]

## [6.2. Taxonomy](#table-of-contents)

In [70]:
TaxonomyData

,SpeciesID,AcceptedSpeciesID,Species,AcceptedSpecies,Genus,Family
0,SP1,SP1,Ostrinia nubilalis,Ostrinia nubilalis,Ostrinia,Crambidae
1,SP2,SP1003,Zeiraphera diniana,Zeiraphera griseana,Zeiraphera,Tortricidae
2,SP3,SP3,Plutella xylostella,Plutella xylostella,Plutella,Plutellidae
3,SP4,SP4,Helicoverpa armigera,Helicoverpa armigera,Helicoverpa,Noctuidae
4,SP5,SP5,Spodoptera exempta,Spodoptera exempta,Spodoptera,Noctuidae
...,...,...,...,...,...,...
1465,SP1466,SP1466,Hypena commixtalis,Hypena commixtalis,Hypena,Erebidae
1466,SP1467,SP1467,Syndemis cedricola,Syndemis cedricola,Syndemis,Tortricidae
1467,SP1468,SP1468,Mimudea puralis,Mimudea puralis,Mimudea,Crambidae
1468,SP1469,SP1469,Typhonia melana,Typhonia melana,Typhonia,Psychidae
1469,SP1470,SP1470,Notioplusia illustrata,Notioplusia illustrata,Notioplusia,Noctuidae

In [71]:
TaxonomyData = TaxonomyData.reset_index(drop=True)

In [72]:
cur.execute("""CREATE TABLE IF NOT EXISTS Taxonomy (
    SpeciesID VARCHAR(7) PRIMARY KEY, 
    AcceptedSpeciesID VARCHAR(7),
    Species TEXT, 
    AcceptedSpecies TEXT, 
    Genus TEXT, 
    Family TEXT,
    FOREIGN KEY (AcceptedSpeciesID) REFERENCES Taxonomy(SpeciesID) ON DELETE SET NULL)
    """)

In [73]:
cols = ['SpeciesID', 'AcceptedSpeciesID', 'Species', 'AcceptedSpecies', 'Genus', 'Family']

In [74]:
BaseTaxonomy = TaxonomyData[TaxonomyData['SpeciesID'] == TaxonomyData['AcceptedSpeciesID']]
BaseTaxonomy = BaseTaxonomy[cols]
BaseTaxonomy.to_sql('Taxonomy', con, if_exists='append', index=False)
con.commit()

In [75]:
ComposedTaxonomy = TaxonomyData[TaxonomyData['SpeciesID'] != TaxonomyData['AcceptedSpeciesID']]
ComposedTaxonomy = ComposedTaxonomy[cols]
ComposedTaxonomy.to_sql('Taxonomy', con, if_exists='append', index=False)
con.commit

In [76]:
Taxonomy_check = cur.execute("SELECT * FROM Taxonomy")
Taxonomy_check.fetchone()

('SP1',
 'SP1',
 'Ostrinia nubilalis',
 'Ostrinia nubilalis',
 'Ostrinia',
 'Crambidae')

In [77]:
#cur.execute("""DROP TABLE Taxonomy""")

## [6.3. Area - Geographical Region](#table-of-contents)

In [78]:
RegionsData = RegionsData[['AreaID', 'AreaName', 'Country', 'Continent', 'SubContinent']]
RegionsData = RegionsData.reset_index(drop=True)

In [79]:
cur.execute("""CREATE TABLE IF NOT EXISTS Regions (
    AreaID VARCHAR(8) PRIMARY KEY, 
    AreaName TEXT, 
    Country TEXT, 
    Continent TEXT, 
    SubContinent TEXT)
    """)

In [80]:
RegionsData.to_sql('Regions', con, if_exists='append', index=False)
con.commit()

In [81]:
Regions_check = cur.execute('SELECT * FROM "Regions"')
Regions_check.fetchone()

('ATA.1_1', 'Antarctica', 'Antarctica', 'Antarctica', None)

In [82]:
#cur.execute("""DROP TABLE Regions""")

## [6.4. Realms](#table-of-contents)

In [83]:
Realms = Realms[['RealmID', 'Realm']]
Realms = Realms.reset_index(drop=True)

In [84]:
cur.execute("""CREATE TABLE IF NOT EXISTS Realms (
    RealmID VARCHAR(5) PRIMARY KEY, 
    Realm TEXT)
    """)

In [85]:
Realms.to_sql('Realms', con, if_exists='append', index=False)
con.commit()

In [86]:
Realms_check = cur.execute('SELECT * FROM "Realms"')
Realms_check.fetchone()

('RLM1', 'Nearctic')

In [87]:
#cur.execute("""DROP TABLE Realms""")

## [6.5. References](#table-of-contents)

In [88]:
References = References.reset_index(drop=True)

In [89]:
cur.execute("""CREATE TABLE IF NOT EXISTS "References" (
    ReferenceID VARCHAR(7) PRIMARY KEY, 
    BibliographicReference TEXT, 
    ReferenceYear INTEGER
)""")

In [90]:
References.to_sql('References', con, if_exists='append', index=False)
con.commit()

In [91]:
References_check = cur.execute('SELECT * FROM "References"')
References_check.fetchone()

('REF1',
 'Li, A., et al. (2024). Sugarcane borers: species, distribution, damage and management options. Journal of Pest Science. 97(3): 1171-1201',
 2024)

In [92]:
#cur.execute('DROP TABLE "References"')

## [6.6. Natives](#table-of-contents)

In [93]:
Natives_DB = Natives_DB.reset_index(drop=True)

In [94]:
cur.execute("""
CREATE TABLE IF NOT EXISTS NativeDistribution (
    SpeciesID VARCHAR(7), 
    RealmID VARCHAR(5), 
    Continent TEXT,
    Cosmopolitan INTEGER CHECK (Cosmopolitan IN (0, 1) OR Cosmopolitan IS NULL),
    ReferenceID VARCHAR(7), 
    FOREIGN KEY (SpeciesID) REFERENCES Taxonomy(SpeciesID) ON DELETE SET NULL,
    FOREIGN KEY (RealmID) REFERENCES Realms(RealmID) ON DELETE SET NULL,
    FOREIGN KEY (ReferenceID) REFERENCES "References"(ReferenceID) ON DELETE SET NULL
)""")

In [95]:
Natives_DB.to_sql('NativeDistribution', con, if_exists='append', index=False)
con.commit()

In [96]:
NativeDist_check = cur.execute('SELECT * FROM NativeDistribution')
NativeDist_check.fetchone()

('SP1028', 'RLM10', 'Asia', 0, 'REF1')

In [97]:
#cur.execute('DROP TABLE NativeDistribution')

## [6.7. Observations](#table-of-contents)

In [98]:
Observations_DB = Observations_DB.reset_index(drop=True)

In [99]:
Observations_DB

,SpeciesID,AreaID,RealmID,Cryptogenic,IntentionalRelease,Introduced,Dispersal,Established,Eradicated,Year,ReferenceID
0,SP1,CAN.1_1,RLM1,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23
1,SP2,CAN.1_1,RLM1,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23
2,SP3,CAN.1_1,RLM1,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23
3,SP4,BRA.1_1,RLM2,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23
4,SP5,SYC.1_1,RLM3,<NA>,<NA>,<NA>,<NA>,1,0,<NA>,REF23
...,...,...,...,...,...,...,...,...,...,...,...
17461,SP576,JPN.1_1,RLM5,0,0,1,0,1,0,<NA>,REF780
17462,SP576,MDG.1_1,RLM11,0,0,1,0,1,0,<NA>,REF780
17463,SP576,KOR.1_1,RLM7,0,0,1,0,1,0,<NA>,REF780
17464,SP238,USA.1_1,RLM1,0,0,1,<NA>,1,<NA>,1976,REF15
17465,SP238,PAN.1_1,RLM9,0,0,1,<NA>,1,<NA>,<NA>,REF15

In [100]:
cur.execute("""
CREATE TABLE IF NOT EXISTS Observations (
    SpeciesID VARCHAR(7),
    AreaID VARCHAR(8), 
    RealmID VARCHAR(5), 
    Cryptogenic INTEGER CHECK (Cryptogenic IN (0, 1) OR Cryptogenic IS NULL),
    IntentionalRelease INTEGER CHECK (Cryptogenic IN (0, 1) OR Cryptogenic IS NULL),
    Introduced INTEGER CHECK (Introduced IN (0, 1) OR Introduced IS NULL),
    Dispersal INTEGER CHECK (Dispersal IN (0, 1) OR Dispersal IS NULL),
    Established INTEGER CHECK (Established IN (0, 1) OR Established IS NULL),
    Eradicated INTEGER CHECK (Eradicated IN (0, 1) OR Eradicated IS NULL),
    Year INTEGER,
    ReferenceID VARCHAR(7),
    FOREIGN KEY (SpeciesID) REFERENCES Taxonomy(SpeciesID) ON DELETE SET NULL,
    FOREIGN KEY (AreaID) REFERENCES Regions(AreaID) ON DELETE SET NULL,
    FOREIGN KEY (RealmID) REFERENCES Realms(RealmID) ON DELETE SET NULL,
    FOREIGN KEY (ReferenceID) REFERENCES "References"(ReferenceID) ON DELETE SET NULL
)""")

In [101]:
Observations_DB.to_sql('Observations', con, if_exists='append', index=False)
con.commit()

In [102]:
Observations_check = cur.execute('SELECT * FROM Observations')
Observations_check.fetchone()

('SP1', 'CAN.1_1', 'RLM1', None, None, None, None, 1, 0, None, 'REF23')

In [103]:
#cur.execute('DROP TABLE Observations')

## [6.8. Close Connector - Database Conclusion](#table-of-contents)

In [104]:
con.close()

In [105]:
os.rename(r'../Database/ENNLWD.db', r'../Database/ENNLWD.sqlite')

In [106]:
con = sqlite3.connect("../Database/ENNLWD.sqlite")
cur = con.cursor()

In [107]:
tables_check = cur.execute("SELECT name FROM sqlite_master")
tables_check.fetchall()

[('Taxonomy',),
 ('sqlite_autoindex_Taxonomy_1',),
 ('Regions',),
 ('sqlite_autoindex_Regions_1',),
 ('Realms',),
 ('sqlite_autoindex_Realms_1',),
 ('References',),
 ('sqlite_autoindex_References_1',),
 ('NativeDistribution',),
 ('Observations',)]

In [108]:
con.close()